### ISSUE TITLE
Overly aggressive de-indentation

### ISSUE THREAD

**Issue by SteveGilham** [fsprojects/fantomas#2110]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKENgDaIC5gCdEBnAVy3wF4AdA6gO00wEl7jcDSBbRe3AOmb8Almw7deuAIa5hsegDVhxYblgEw7GYgDkYAG7LVieLQZnGTXCVwWmGADwABMMEIly%2BAO6qAFnftAsAAlRDgCeFEAcwBZPF8EUIAzMBo6SyDAtyUVKjB6ciwAzKCABVJiX1T8wuKS%2B1LYAAdqgqwsMABfLuq3LWs9H1x-dPqx8cwYhHJEZnhqpCT%2BGKlRKfgZ5cN4fgAVWABlDmiACgBKOomrwNDwyPpY%2BIRqw1zL64%2BIW-V7x%2BHExApNIMT6gpjZIx5NpFUZguEQcqVVq1WHwsGNFqUGrtHrdJwAPgskAANOAoMQ8LIHsRUGAANpkiCgeyQAAkuAAnk1kGhIKJcCTGRg2fopFhSDz6ULMAAGUlBSCsJB8A7CABeyHlgQATNKwABdIWdLVMvVsznc2l8viClms0XiyUMoIARhNTEgKwAHgAZUSIH28KLDW2BACcMr1hswxqFzI97K5ksgvHgAHkkn76IgjhycKHMCKxRLac6de7CwBRejpzP%2BgserBJSBRo3u%2BOFxOW3kAI1gsCwDYgRcdpb1EAAzBXhawKQRcAAxURigByiC8WHr04g4kQrZj7bNXeTfYHQ6g9uLTvHYAALNuoAdEFxhHAsPIAIK4au1rOam9JGKFL7hgsaYB2wrHlap6DtOI4lmgZb2AArA%2BkAHE0UjQIgABCgLqIgpRSAQUg8NYBDnjunB7vY0agYedoWie-awUeDoIVKQQAGxoRhWG4fhRA%2BrAXiIAQ0BSBSrD6LAEmyPIlFgLuIEQGBGAQcOUG9ix57wdeQQAOy8Zh2F4UkBEAKpNNy4mSbM9AyXJcj0IpgFYMBtFtnGR5MdBOlwZeo6ITeAAcxn8WZBEAMJYJJxBRfI7CcNAagUQ%2BbkeUwdGqQxCa%2BdpZ4Bex%2BnhuFpmCYgcRcD2YmuUBNFZV54E%2BUmfmFWxV5jq6co3uhJkCeZRAJe%2BLnpfVKldLlnb5VAMG6YFHFIUwLpur1fHYR%2BSTkQlXBcFIinKZ5B7eYxrUFaxdrFV1gQutqZUDQRT4vm%2BClje5DWYNlk0nXlZ2zf5HVBZxN1Tmt-WbeRT2vgOr03odjXHc1p3dv97WXZ1wWuvevVKpIab0LsBAcgA6n4dXvRNammsjzFowmV2YzdqFg-xH4ELApA1gAIogm4vuRB3UZTU2QTN1oCkVGPA-YLo8b13rMEkuy%2BLwlbvQcCTzqT8Ahg%2Bt6Rkd9E-dNf3i-NDPS8tRny1IXqsEkwhemmNkyOolZek0RDECosNBMhBsI0bSO-SjZuS0DS2YC6YU2163wRNrus3vrwvG6Lpv8ubUuRxgLphmh3rx-AK7cDVBAZsw1hcDSD4uqnwcm6HXCeMIm7Zgu6h7bg5G7K14eLTe2o9QqRcxC3beIB3BBdwLaHQL4xFYeRAD6Pg674LaGzlaeaWLmf9yV9jaqtCremzJEcmmBB%2Buwicb3rAefU16ktaH%2B%2BAwPQTandsfn1Il-X2ULgEu1UxIVyrjXG8dct7fQbunJu49-RTxnmJXuloD7XSPqDBUf8AE31wGPCgrckGdxkLPXq89F4pTEqvYQ69N6B23nA3eGcbQYMZkfbGp9bYKCvDhUQvw76KRCo-DAX0qauFfsmd%2B6MI6D2Ztwr0C5OYpWcvwms0QhEP3ri-GmVoZH02zoPOWiiuawFwAAcTwO7T2JAfb0C0Tef2OjqYh1phdQxciv7W1Pog7MOF3zQAANY4RIsEvAxB8YHFIogYa3BRoAXGjAiRGkLxizmuwy2mBtQxwVGuDc-o8K4FErwNBiAeYO3oKoZyH4axVTLpAoIGUPpiOfq4xu7is5eJ1PnXqABpRAiAmiK2VrwVg0SeB-nJplJ%2BiNdFuP0Wwj%2Bh8mATmHoET0ts1YvkqI4oIKdkkixYaHDJyzMGrJPhs1UDwcBsyiBIPgxNEA9nWP%2BJpSTGGwPmR0tqHjOwWxzpOH%2BODNxRHoMo%2Bgqj5CqjBTIUgRB9i4z4DIZy0yWkQHEUctJptTmyM-oECc2CNkfgoGJegKL9ABnkI8UBBAKmiGqYlNFLjJF6POl0-F9gJxcI2YQ2Qf4fSkR7PAKQMVYAqAePkiezLDk72xScgGeKVmYAnAojZXNlBSB7DgbZyhfAHA5Mir0MrPkpKkb8jlyqMAThMRsgZQykW4FYKEqQkL76JIprK5h8rOmZMBWACcPiNkBNdUEv8xA2YcxrGudgJg%2BXEOzDYr29jGmBHhrMoO3z4G%2BrORw1ZuTg3EUikQDVxBoAEGEC%2Bcl1h4AWSqfIHm0BYokXkgk95nrTVYvNDixVnjOWrN6QqI4FaUqvJNRm1SZJ9Raj5MQBcKhaTNJAJ0IAA)

#### Code

```fsharp
      let result =
        Instrument.I.instrumentationVisitor state' visited

      test
        <@ { result with
               RecordingMethodRef =
                 { Visit = null
                   Push = null
                   Pop = null } } = { state' with
                                        ModuleId = def.MainModule.Mvid.ToString()
                                        RecordingMethod = visit
                                        RecordingMethodRef =
                                          { Visit = null
                                            Push = null
                                            Pop = null } } @>

```
            

#### Result

```fsharp
let result = Instrument.I.instrumentationVisitor state' visited

test
  <@ { result with
      RecordingMethodRef =
        { Visit = null
          Push = null
          Pop = null } } = { state' with
      ModuleId = def.MainModule.Mvid.ToString()
      RecordingMethod = visit
      RecordingMethodRef =
        { Visit = null
          Push = null
          Pop = null } } @>

```
            
#### Problem description

Overly aggressive de-indentation leading to many offside errors

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 1/1/1990

```fsharp
    { config with
                IndentSize = 2
                MaxLineLength = 90 }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello Steve, thank you for reporting this issue.
It appears that to maintain valid code, we would need to lock the column of the record update expression.

Potentially add an additional case in
https://github.com/fsprojects/fantomas/blob/ef132c18560c104a26efdac518b834fde896e150/src/Fantomas/CodePrinter.fs#L1671-L1674

I'm not quite sure about this, but that would be my starting point.

Are you interested in submitting a PR for this?

**Comment by SteveGilham** [comment]
I'd have to learn my way around the codebase -- I've not peered under the hood here before.

**Comment by nojaf** [comment]
In case you are interested, I've made some videos that explain a bit how the code in Fantomas works: https://www.youtube.com/playlist?list=PLvw_J2kfZCX3Mf6tEbIPZXbzJOD1VGl4K

**Comment by nojaf** [comment]
I believe this problem was solved via https://github.com/fsprojects/fantomas/pull/2513.
A regression test could close this issue.

**Comment by SteveGilham** [comment]
[The file from which this example was extracted](https://github.com/SteveGilham/altcover/commit/82098d9a15177d7d078ace896d8f21386c3eab51#diff-b8eb3ac4a6f8cd76e40bb7ddd4dbfe52d96c0b05d573b266ae27e1c3c6da074e) now simply yields
```
Processing .\AltCover.Tests\Tests2.fs
Formatting .\AltCover.Tests\Tests2.fs lead to invalid F# code
```
with no further hint as to what was detected; so I cannot currently state whether this issue has been resolved.

**Comment by josh-degraw** [comment]
If you pass `--force` to the `fantomas` command, it should force it to print the output and you should then be able to see the output even if it is invalid.

**Comment by SteveGilham** [comment]
Having used `--force`, I see the issue still recurring with fantomas 5.0.0; presumably this is what was detected as invalid code.

So far, alas, I have not been able to create a cut-down example through the web tool.  The configuration I'm using is [thus](https://github.com/SteveGilham/altcover/blob/cd73e556ad33addf0a701ab689d3dcbd6ae9b0aa/.editorconfig) -- the only customisations I recall making since it was generated are the first two lines, 
```
indent_size=2
max_line_length=90
```
but I notice several differences in width parameters compared with the tool defaults.  Tweaking the tool settings to match the `.editorconfig` still did not suffice for a repro, though.

Related indentation issue (just warnings here) [this sample](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKEMYCKwC4DlFcA6XRAZ1wB0AnKgO0yYwAoAzAV0YAcwBaAHy0GzUaxbAw3YgHUAlrgAWAYVgBbNbHosA7gsUzYNANZz6AcyxyaiaLiMBPAGoBZMFUgB9AJLlyHRAAmAGYPAEowPSVhRjE4%2BITEpLjVejY5cw4aAENcOS0wAF4wHAIiYgAhDjkAG3hU9MycvK1iLEQAIw5zGOS%2B-oGE-Fgq2vgisDZsmvJEMABfMN7BiFl9AEEa3FUAN0QaAHluFvpyZZXubgAGc8HoaBu6WJWAMSNoRAAVGgClp5WwGslJttrA9jRvGpuEZcC4EBwaogWH8RCsgYoQbt9gBxIhOfbkfLaFHPJIAHwEYDIlHkSmUABlvOsaJk1Ih6LhyCTEh5eU9IAAacBQWa4PIWcioMAAbWFEFAzEgABJcA5uMg0JAzLhBXKMMqdtMAlLZWIrkKxJBvPQkByAMpyABeyAtokCeogAF09fNXfKPVAVWqNVBtbrFUrDTVjWhTaIAIx%2BpiQFzZAAe9LMiHp7PMSnDogAnFcA97ML69Qrk0H1VLIOz4Ac2Jn6Ig7arEQXMAajSG48xAknuwBRG1NlsugMQSA1NiQUs%2BpNV7s1kOQDqwWA1Lv6yO9k1TsDBIf662zGi4F5maaEHQ1LM7zC4H6IBflpcB5Wq2uajdbx%2BBlGMYyoeAAsJ7Tna3DZB8FSIGwRiIAACtkORsmQNAARAz4BG%2BGAVpgy67t%2Ba5-tuJ49tGfaHgArBBUBQTBiBwQhNj0rAOj7NA2SzNaOywNxJxYVSL54RABEYER06rnWZEAZRwH9kwABs9GQIxsHwYhACqlxcTxiB8QJuREsJUwzK%2BzBlvhH4RiRsmbuRn57lRB5iAA7GpGnMVpNjKDUPHkKklA-HYRhmdMsxiQstnVvZv6OfJLmKYeAAcXnQZprGIC4iBqB0%2BwRRZ0USf6dnBg5-4Ucl1FiIWGVMSxiGqDUWhFVFVmLpWznxVAcnVUBtUJuah7qZliDrGwGGqBo2TCThllMNZ4mxSuvXrolA37rGh7xomo3eU1Nh2nlchwK19DtYtmDLTF3XlT%2BfWbc5g1uQmg4HeNk0YSdahnVubX0QtJWrcRFUJVVL3bSBYjxsen1McysBcPA7T3n9GHzaJnXvvdcXg6GHJJa9O2w%2BBo2pmm3hsJ8ijsnaigwvI8D5vRJY4zZeNrQTWpE1trmkwmdEU%2Bm1O0%2Byw4WQzTNyCzijCaB7NLV1hE9TzYb8ylsOqSLVNpHIaZHPsuRGMOabcDYfimfRNFKzdKuSWrj28zqmtDcw8aebrABKthGPAzOs2BdsYLdpVgFJgbrRrUMCzDCbpT7fs0PA%2BAcPl%2BxNt4ZBqJK9HxiDXNg87agInk96tm8NBqLkGGfBVbtvR79Wjb7cApy4Ze1FmVc12KhVqdAiioTBGGeHocvzhzK1F9J0d87HWtuiNlqU8yOQOAcNCZjSstB2IiuF6rD1rjHEYk-HA77av6br9km-b3IlBpxnhxsNneV57tR%2BOyfdal1sbulcjB9zrg3Re7smCBA%2BpaO%2BD8d6wi7hXRAvda4D1GkPEedh9jjz3vLH%2BZV8bOzPtWC%2BSlMAhDUpTJwvYKhmHgGYcwgd5b0UPtPO6x8iGnwXufaG5CMCBHJjfNMLwuB2CJHQm0jDmEKxDl6B2hDubEJ4aQvhh5AjC2EaUXEuAzYWwoISLQMibZyLAGHUGc8eb9QgU3KBOtV5IKzBUVq0BjAVByK4og5ADj0DtNkNkLV06XXouZDqytcacKUaRZ6vC478IgIEL2lpbzILgrgTi7J67qnaOkegCgiTrBtLlV%2BX8xChOuqHBREcnbRMhrEpeA5E6wPvOYegoj6DiK0A6VpuQshfFgNaW0uATKA0POUgh1S-4QycvUyBFCW7NIwvQEyex2IWGKQVGgOSzD5K0KU0Q4z2Hh0jl%2BKxMTVFxMPMEFeogUxdwnPSfxHR4DZH8rAQkFgUkPhCZFCp8iIm-y4ZVGZFyGlMGCNfW5ej9hyDZByaYABpRAiBuCDPZLga07jsgdJYWM35EyTkyWmcTNRYhggwNuc47FxgJzkCRijQglBEDwE7oA5BejLaGNOFjXCRyLFRzOXU0FcyMDBHhpaCoqEjqICsOQaANBYXXjIPAbSeStDtGgAFZo1s8XFT5bPAVztrGzNsZgYIQioXmxhXC4ZNR2w0GRiFDg3B2wOE7D8vV4TOaROLtw12NjBbMGCJo25SKUWUxfpspsVL6A0qzPsj2VxTHmINaco15yVxkKufY259qzqwgQJOMp%2BKjnCk9K6LU5AXiEilOM%2BYQA)


#### Code

```fsharp
        DotNet.test
            (fun p ->
                (({ p.WithCommon(withWorkingDirectoryVM "_Issue23") with
                                                                         Configuration = DotNet.BuildConfiguration.Debug
                                                                         NoBuild = false })
                     .WithAltCoverOptions
                     pp0
                     cc0
                     ForceTrue)
                    .WithAltCoverImportModule()
                    .WithAltCoverGetVersion()
                |> testWithCLIArguments)
            ""

```
            

#### Result

```fsharp
DotNet.test
  (fun p ->
    (({ p.WithCommon(withWorkingDirectoryVM "_Issue23") with
        Configuration = DotNet.BuildConfiguration.Debug
        NoBuild = false })
       .WithAltCoverOptions
       pp0
       cc0
       ForceTrue)
      .WithAltCoverImportModule()
      .WithAltCoverGetVersion()
    |> testWithCLIArguments)
  ""

```
   
Fantomas master branch at 2022-09-20T21:08:34Z - 11c2a862e2b3828627c19ea339f2db48d556e268

```fsharp
    { config with
                IndentSize = 2
                MaxLineLength = 90
                MaxIfThenElseShortWidth = 40
                MaxInfixOperatorExpression = 50
                MaxArrayOrListWidth = 40
                MaxValueBindingWidth = 40
                MaxDotGetExpressionWidth = 50
                NewlineBetweenTypeDefinitionAndMembers = false }
```

**Comment by SteveGilham** [comment]
Note: fantomas 5.0.2 has resolved the original issue -- presumably why I was unable to produce a repro using the online tool.   

The [related issue in the comment above](https://github.com/fsprojects/fantomas/issues/2110#issuecomment-1254819388) still remains, however.

**Comment by nojaf** [comment]
> Note: fantomas 5.0.2 has resolved the original issue

That is good enough for me, please create new issues for new cases.
What you list in your comment is a separate issue. Though both do mention a record update expression, that does not mean they are one and the same problem.

**Comment by SteveGilham** [comment]
New issue #2529 created.

**Comment by nojaf** [comment]
Thanks, I prefer to close issues when a regression test was added.
