### ISSUE TITLE
Improve formatting

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/fantomas#501]
(Sorry for the non-descriptive title)

### Description

The following is hand-crafted, and I find it aesthetically pleasing and tidy:

```f#
module Program

open Microsoft.AspNetCore.Hosting
open Microsoft.Extensions.Hosting
open Serilog
open Startup

[<EntryPoint>]
let main args =
  Host
    .CreateDefaultBuilder(args)
    .ConfigureWebHostDefaults(fun builder ->
      builder
        .CaptureStartupErrors(true)
        .UseSerilog(dispose = true)
        .UseStartup<Startup>()
      |> ignore
    )
    .Build()
    .Run()
  0
```

Here is how Fantomas formats it, which I find rather messy:

```f#
module Program

open Microsoft.AspNetCore.Hosting
open Microsoft.Extensions.Hosting
open Serilog
open Startup

[<EntryPoint>]
let main args =
  Host.CreateDefaultBuilder(args)
      .ConfigureWebHostDefaults(fun builder ->
      builder.CaptureStartupErrors(true).UseSerilog(dispose = true).UseStartup<Startup>
        () |> ignore).Build().Run()
  0
```

There are several issues here:

* I'm not fond of the (initial) fluent calls to `Host` being aligned the way they are. If `Host` had a much longer name, all the interesting code would be pushed far to the right, leaving little space and yielding many unneeded line breaks.
* The body of `ConfigureWebHostDefaults` is indented on the same level as the line above. It should be indented an additional level.
* There's a weird line break after `UseStartup<Startup>` with the `unit` arg being on the next line
* `.Build()` and `.Run()` should be on the same level as the other fluent calls to `Host`

### Repro code

[Online](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview-trivia&code=LYewJgrgNgpgBABQE4gOZIIbALACg8gAOMAdnALICWAxigM4gBmALgHQCCdhAcjMwMIgkMVgAkQdZpRKoCxMlVoSmbAKIAPZqTqUQJOmIlSZc0nADKMJJShpTZc8wxJmEQnjwBtADyqSzJABPBBBpZgA+AF08WGY4YAxpOGdUOjgAXjw4OHFJLOy4Vn5hDC0AERhGDGhmACEIGzArAAoUugBKfOyivUZKVAhhAHUYACNc5gqqmrpmxggyUYaoJqQ4AFpwroKlxqttgsL+DEJXYUdnV0JVJBQkWYCIGE7cQ8PWAFU6GEtrW1RmmBKFwJPB0nBHs8DgVPt8Li43N54Vdws0Xm84AAfcJwfokIQwbbomH1Rpo7asABKC3JrzgAAY8EA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXAEwC+QA) (on my PC the line width it set to 120 when clicking the link; I made it with 80, so that's probably another bug)

**Comment by nojaf** [comment]
The thing I'm missing somewhat here is when not to stack them on multiple lines.
For example:
```fsharp
let foo = Host.CreateDefaultBuilder(args)
```
As this is short, I'd leave this as it is.
First options that come to mind here are:
- extra setting to control from what length it should start the multi line approach.
- Or do respect the MaxWidth of the page here to determine this?

**Comment by cmeeren** [comment]
An extra setting would be the most flexible solution, similar to e.g. `MaxInfixOperatorExpression`.

**Comment by nojaf** [comment]
How about `MaxChainedExpressionWidth`?

**Comment by cmeeren** [comment]
Sure, that works. Could also consider a name containing `Fluent`.

**Comment by quintusm** [comment]
The lack of this functionality is my only major issue with Fantomas as it stands today.  It would be great if we could have something implemented for this.
Personally I could live with an "always stack chained calls in column" in setting, even if it leads to splitting short lines such as 
```
let foo = Host
             .CreateDefaultBuilder(args)
```

Thank you very much for all the great work being done....

**Comment by cmeeren** [comment]
I agree with @quintusm; this (as well as #988) is what prevents me from actually using Fantomas. After these are fixed, I'll probably be able to format all my codebases using Fantomas. Before that, the Fantomas formatting would require enough manual tweaks for me that I'd rather wait.

**Comment by nojaf** [comment]
Hey @quintusm and @cmeeren, thanks again for expressing these missing features.
I can't really say when I will get to those but reminders are good nonetheless.
In #420 I've implemented a feature to ignore certain files when formatting, maybe this can be of use until I get to the other stuff.

**Comment by nojaf** [comment]
I've pushed the first alpha with support for this issue at https://www.nuget.org/packages/fantomas-tool/4.2.0-alpha-001.
See [docs](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#fsharp_max_dot_get_expression_width).
Please try this out and provide feedback.
Thanks.

**Comment by cmeeren** [comment]
Looks good for the most part, but [this fails](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKEA2iAuYBmAlgE4DO2AcgIYC2iYAvADpGMB2EEShrizbHHAHQBBbNiIEARgFdsvFuwFhBABUqlE8AEqISACgBixMlVqCAbpQzTEAGjBHSFGokHQiiSnICUfRQMEAcRw9PGl2aTAAWgA%2BMGlBRxMXXwUlZQBlHB19aRJEIiyxArAAVXyiQXzsJOdab0hbcChq7AJWAHMSVDAAbWaIUHTIABJsAE8AB2Q0SHbsRoGOUctrGb6lgQAGJvSISABJViRWbAyCAC9kXb2AFk2wAF0lgF8bwYfRiemeudPF4YjVY2Hr9PZgACM7yUkAAspQAB4AGXaiCRiE62AAFgC9hCAExbB7PARvJZDGFjKbrSCSWCwDC4gQrKwgtBgvb46HMrLUAhwDCwViiACixwA8ngUTwmUo8FZ8sTXtCKcyqT9ZnSGbL9kDWesOekAMzc5YZSaUaCIABCiDwsA8aiILjkRB1HHENiVpJVn3VNK1jNNLLWoIeEFupv25stNrtDrRsAA7gVoJR8kdzLA020he6IJ7EN6OGSBKrlv7foH3SG2RtwQBWKNQGNW232jylSbTIhpjOsLM5gh55vyjCK9Ikku%2BwHfAP0oN%2B4EG8NgABszcgrbjHcQAGEMOmSHuhWQiNJoNgHfn8Aqi5PleS-XOqwua3rQ%2BzVwB2Tfb9sJrCiDUJIBQ3mOE5KFOEClhw5a6i%2BmpvsGH51oaSgABx-habbxh4J6Cqw4F3sWMEzpSiFQNWKHLmG4IAJzYbGwh4K6J7UNQlA3oWpFgLBHyztSr7ajR%2Bp0XiOyrluOE7gmvL8gyI6rhB95QY%2BZbPkJSEiUuYlfuCEJQlJ24sa68kCkp4I8Q%2BPpPoJGpUchumfvWeJclJRwnNg4qsAAKkQ4wAOoENixHjqpAjQXx5FqpRtJOYCtH6XiJrGTJwhELA4TwAAIogGAEHyrrceeEUcFF-FgPBUCVrM8zvklrnpBCkZSfCCIHHgvlYhiIrhRkWIOtgwXwKFza3ESNnTnZFFaVA9WiS56ECBCTZtYiRyEAi4o9l4DoigikweCQJDDkRzYNpNam2Rp9k0gtzloauEIbutCI6HARDwCNY2rhNvGVdVXxzX8CyLU9Bm-m9GXOuM4pECiZA-Ti41XZF6lwZpDmgw1elNUoEJYW9ABq%2BrWu08DtB0yM3v9U1kTNsUgw9iV48tHAQoxb0GOEl5neTxxUzTqMAzFFZxSzlKNezECEpu7U5bA2DBNgB1Hbop1CsLq6XaLjPiyD1GPSu4L4kZ4JwtIGBtAVPDWoK0AANbWs6Ts4CQPkZC4BHSNQ53KSR9PRfrCGGwlUts6u%2BLuRb5CIEmttxtgKYYr51J5dwIVncIxxASBBTdKOgfXdNt2zdjRus0tUepRbADSiCIJMnXdRiRxe7Q0rXAH4V62XTPY5LarS1HrUW%2B1fV8iQWLa%2BCdMlwz-cGxX4fD5HptrRb5ydFgGUdL7GLDYgkiwgg3fgipfeY3dwmLlXEOcq9FvCAVHSsDzrB80K5xv140geL5WAnlD5eDOmFSC6MbrX3LvOHS98Tacihs-a2BRWCgPMImToedQJEAzu0LOp5wFlQgBVMWocV5wIjtXU2RMt7iH5NgU%2BSAiEA2aI8G4cwSAGFOj0S%2BLwgA):

Original and expected:


```f#
let firstName =
    define
        .Attribute
        .ParsedRes(FirstName.value, FirstName.create)
        .Get(fun u -> u.FirstName)
        .SetRes(userSetter User.setFirstName)
```

Actual (notice `.Attribute.ParsedRes` on one line):

```f#
let firstName =
    define
        .Attribute.ParsedRes(FirstName.value, FirstName.create)
        .Get(fun u -> u.FirstName)
        .SetRes(userSetter User.setFirstName)

```

**Comment by nojaf** [comment]
Published [alpha-002](https://www.nuget.org/packages/fantomas-tool/4.2.0-alpha-002) that tackles this example.

**Comment by cmeeren** [comment]
I can't reopen, but [something is still not right](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBzbAwrOumALwA6AThQHYRIBmAlrYtXRBAHQDyADoioBDLM1i0O9LtwBisKkVpZEADywAKJSvXcssAIIBXLAAtEy5tFGJ42tVgCUUrmG4BxQsUzQxEjYxG9AD6YPzCVADOQmAAtAB8Lq5gmDiq5GAATEmuqo6QADTgUNFYYrS4kahgANrFEKDJUAAkWACegtWQrFiF9VyQzQBuwuhGyGh1TRAADEXTUACStEjKAMrMAF7I89OZ-RAAuv0AvrsNBy3tnWjdyn1NgyNjE7WXEACM58mQALLCqgAMqxEICLLgzA9ph9MjNLsdXGd%2Bo0fq0Oq9IAAjWDEKGuJ6jcbVKZ7b74taIAC2VmIEgMWAAoiteIxgWw8clGKNovDTt8Ufi0TcoNjcWSWs8iZN3mAAMziiCQNbhaCIABCiEYCkQAAUIsJKdghBzXFgqONeYj%2BZdBtcMaL0CaJYTXiSmgAWBVQZXCVUarVUUGwADuQms0WWQ1g1j8tCdEDNFqaCK4SNcAoGQvtOMd4oJL2JMoArF6lSr1ZrtQBVfiCKjhxCR6OicRxr1c9A85N85E2rNdB1O-NSt4LABspZ9fsrgYI6GEkUiSkiid8CnjYA7XeSKYgaa4GcV-dug7zwxdhYWAHZJ%2BX-drflTMcb29zEJbU9bHseRTmh%2BeC2lBYAA5b19CsA0QIh0AkDct3fbsrV7b87QHP8z0lV0ZQATjA1UDEYFRFFgSlKWEDdEwQnce3TPtUJPdC%2B0wy9oTmGUy3A%2B9Awpak4BgtsZXgj89y-VF6N-MUmIvIDoS%2Bdip0QAiiJ4ml%2BIo80qNcXcwH3C4UPRNDJO-ZiZKaGFS2WVYsF4WgABUqDaAB1ZhIVfTtNK4bTdLAQ8rgMhijNREzR2heV5PLAwqFgIJ4AAEUQdBmGpIj1KTaikNo-ThTuXoMOkkKzM9dj-lURZGFs8xaAZdy1lMBQsGc%2BBXJld04UQz9kLE-yoB6f9grdZIPhLYqAWWFhVAEIRRAUBlVH4QNF1bDciza9KOsyrrst6vLAIKwaJxG1QACVEDgKh4Ea5qFla4SdNEwVxJyvr8oG1wPhvQ7IpENpeCoYEV0u0wNxu9qRM6h7uqenaR1ergPlAw6ADUXTVVh4FYXBAeB1atJog86Mh7apN22HPlww7ZCCXxW1RlYMaxr0QbWsGNohrb7mhrCFlhUsSti2AsE8Rk5oWyJWwZ4scc8vG9M27NAsFfqZUyOSFj%2BIx0DERK2DVGDoAAazVEQDewSIbLWA0oOIIxKQEhYhNBu7wczR7T2JmHlcyUsADlEGDbWKywUMLFs9F4pYWgXNbAwVkfSlnyiOC31u7zfNtSG3eMl7lbCtWAGlEEQfgyoqixlgtw02R2QTk8d1OCfZ3L3a5vYirVkrqupSJTAl66paOGWfIb%2BXc2blimkyYa1Y2CpMEi3AbYsBrEExX4EGr%2B3a%2BZp3WZdjPGKzknlYOtWDES3BaEp2hqYkDYL9EIxA1s2BLKXltYLc7dcYy-GspH56j7cw%2BqfTWQhaAtiGEGCoccE7h1YFHCQVRP4eQHj-WWbN-6c3HskTICNp5misFgNeSAk7uRTsUQ4uxuiRFkGLaoQkThAA). Function bodies are not always indented correctly:

Original and expected:

```f#
let getColl =
  define
    .Operation
    .ForContext(Context.toAuthenticatedContext)
    .GetCollection(fun _ parser ->
      let x = 2
      x)
```

Actual:

```f#
let getColl =
  define
    .Operation
    .ForContext(Context.toAuthenticatedContext)
    .GetCollection(fun _ parser ->
    let x = 2
    x)
```

**Comment by nojaf** [comment]
Published [alpha 003](https://www.nuget.org/packages/fantomas-tool/4.2.0-alpha-003), let me know if I need to reopen this.

**Comment by cmeeren** [comment]
Looks good, thank you so much!
